### PR TITLE
[lab-reading-stats-concepts] A/B testing exercise missing

### PR DESCRIPTION
**Pull request by anafrs**

### CODE REVIEW

**Comment by anafrs** [comment]
done, without the ab test.

**Comment by ta-data-lis** [comment]
Lab checked OK. 👍

A/B testing is an important concept in the tech world. You should try to answer the third challenge when you have some free time. Did you have any trouble understanding the logic of A/B testing and how it works?

**Comment by anafrs** [comment]
Hi, 
I used to recommend A/B testing in my previous job in a marketing agency, I feel confident I would be able to do a similar exercise.

I found the question in the lab hard to understand regarding the A/B testing. I'm not sure if I have to read the 4 articles and then decide on what A/B testing (different one or the same?) I would suggest. 

For these reasons plus the having to finish other labs, I decided to postpone the A/B testing exercise but I'm hoping to have time to read the articles. 


Thanks,
Ana

**Comment by ta-data-lis** [comment]
> I'm not sure if I have to read the 4 articles and then decide on what A/B testing (different one or the same?) I would suggest.

Exactly, what would you do differently to test.

Fair enough! Do it whenever you can :)

**Pull request closed without merging**
